version: '3.8'

services:
  backend:
    build: ./backend
    container_name: lessonflow_backend
    ports:
      - "17001:17001"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: lessonflow_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend